#!/usr/bin/ansible-playbook
---
- name: Create awsplus database and user on local postgresql instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
   rdsinstance: localhost

  tasks:
   - name: Create postgresql database
     postgresql_db: name={{ item }}
         encoding='UTF-8'
         lc_collate='en_NZ.UTF-8'
         lc_ctype='en_NZ.UTF-8'
         login_user='postgres'
         login_host='localhost'
         login_password='postgres'
         port='5432'
     with_items:
       - 'awsplus'
 
   - name: Create database users
     postgresql_user: name={{ item }} password={{ item }} db={{ item }} priv=ALL
         login_user='postgres'
         login_host='localhost'
         login_password='postgres'
     with_items:
       - 'awsplus'
 
